### ISSUE TITLE
DOCKER_ENTRYPOINT_ARGS is not working

### ISSUE THREAD

**Issue by nil0x42** [C0deH4cker/PwnableHarness#25]
https://github.com/C0deH4cker/PwnableHarness/blob/3c83afb3c0309073c1ff8e3d5e325c4b329940a0/examples/stack0/Build.mk#L196

Even though it's referenced here, it seems this variable has no effect (or i didn't understand it's purpose).

I need my binary to be launched with some arguments. Is that possible ?

**Comment by C0deH4cker** [comment]
Ah, so that comment is out of date. The entrypoint _used_ to be the challenge binary. However, a while ago (2018-2019?), I changed it so that now, the docker entrypoint is `pwnable_server`. This was done to remove all libpwnableharness code from the challenge binary to minimize the impact of hosting a challenge using PwnableHarness. The arguments passed in `DOCKER_ENTRYPOINT_ARGS` go to this `pwnable_server` binary, not your challenge binary. These arguments are processed here: https://github.com/C0deH4cker/PwnableHarness/blob/3c83afb3c0309073c1ff8e3d5e325c4b329940a0/pwnable_harness.c#L542C29-L542C29.

If you want to run your binary with arguments, the best way to do this is to use some "shim" binary that just execs your main challenge binary with the necessary arguments. It can be as simple as this:

```c
/* my-challenge/shim.c */
#include <stddef.h>
#include <stdio.h>
#include <unistd.h>

int main(void) {
    const char* binary = "/usr/local/bin/my-challenge";
    const char* args[] = {
        binary,
        "--foo",
        NULL
    };
    int ret = execv(binary, (char* const*)args);
    if (ret) {
        perror(binary);
        return ret;
    }
    return 0;
}
```

You'll also need to add the main binary into the docker image in addition to the shim binary, and build both binaries. Here's what a `Build.mk` file to do this could look like:

```makefile
# my-challenge/Build.mk
TARGETS := challenge-runner challenge

challenge-runner_SRCS := $(DIR)/shim.c
challenge_SRCS := $(DIR)/challenge.c

DOCKER_IMAGE := my-challenge
DOCKER_PORTS := 1234

# This part is to allow the custom Dockerfile to find the additional built binary
DOCKER_BUILD_ARGS := --build-arg BUILD_DIR=$(BUILD_DIR)

# The first listed value in `TARGETS` is automatically added as a build dependency, but
# we need to add the dependency manually for any additional files that will be copied into
# the docker image.
DOCKER_BUILD_DEPS := $(BUILD_DIR)/challenge
```

This will cause two program binaries to be built when you run `pwnmake` within your project directory. You'll need a custom `Dockerfile` in your project directory as well, in order to install both binaries into the docker image. The first listed binary in `TARGETS` (which should be the shim program) is automatically copied into the docker image [here](https://github.com/C0deH4cker/PwnableHarness/blob/3c83afb3c0309073c1ff8e3d5e325c4b329940a0/Dockerfile#L48), but you'll need to copy the main challenge binary and any other files you'd like manually:

```dockerfile
# my-challenge/Dockerfile
FROM c0deh4cker/pwnableharness:2.0b1

ARG BUILD_DIR
COPY $BUILD_DIR/challenge /usr/local/bin/my-challenge
```

Now, running `pwnmake docker-start` _should_ build both the shim program and main challenge program, build the docker image, and start the container running. When you connect to it like `nc localhost 1234`, here's what should happen:

1. `pwnable_server` will accept the connection
2. `pwnable_server` will fork and then exec the shim binary (`/home/challenge-runner/challenge-runner`)
3. `challenge-runner` will exec the main binary (`/usr/local/bin/my-challenge`) with whatever arguments you put in `shim.c`

This should work with everything the way it is today, but I can try to add a feature for specifying arguments to the challenge binary in your `Build.mk` file. I'll file a new issue to track that feature request. Let me know if you run into any problems!

**Comment by C0deH4cker** [comment]
Closing this issue as `DOCKER_ENTRYPOINT_ARGS` is working as expected, but feel free to continue discussion here or in #26 which I created to track making it easier to pass arguments to a challenge binary.

**Comment by nil0x42** [comment]
Thank you !
